site_name: Raspberry Pi Cluster
nav:
    - Home: index.md
    - Hardware: hardware.md
    - Ubuntu: ubuntu.md
    - MPI: mpi.md
    - Storage: storage.md
repo_url: https://github.com/darrylcauldwell/piCluster